### ISSUE TITLE
Ambiguous operator/ declaration

### ISSUE THREAD

**Issue by LukeStebbing** [behrang/yaml.swift#1]
An ambiguous declaration of operator/ is interfering with integer and floating-point division. I added a simple assertion to the tests to demonstrate:

```
Build test...
Test.swift:844:11: error: ambiguous operator declarations found for operator
  assert(1/1 == 1)
          ^
:0: note: found this matching operator declaration
:0: note: found this matching operator declaration
Test.swift:844:11: error: operator is not a known binary operator
  assert(1/1 == 1)
          ^
make: *** [build/test] Error 1
```

**Comment by behrang** [comment]
Custom regular expression operators are removed. Hope this doesn't happen with other custom operators which are used extensively.
