### ISSUE TITLE
Question: Problem importing library 

### ISSUE THREAD

**Issue by Riccardo99** [behrang/yaml.swift#3]
I added the files ``build/libyaml.dylib`` and ``build/Yaml.swiftmodule`` to my project and added the ``import Yaml``, but I got the following error:

``No such module 'Yaml'``

I tried setting up the Library Search Paths and Import Paths. Changing Import Paths allowed the project to build, but returning another error:

```
dyld: Library not loaded: build/libyaml.dylib
  Referenced from: /Users/riccardo/Projects/PAE/Riccardo_Stable.repo/Build/Tools/QPush/DerivedData/QPush/Build/Products/Debug/QPush
  Reason: image not found
```

I would like to know the the full and correct way of adding this library to a project, so I know I am not messing up anything, as following the Install and Import guide didn't work out. :(

Thanks!

**Comment by behrang** [comment]
Added more documentation to Readme:

To use in Xcode, you have to add these two files to your project:

1. Go to `Build Settings` and in the section `Swift Compiler - Search Paths` set the `Import Paths` to the directory containing `Yaml.swiftmodule` (for example: `/yaml.swift/build/`).

2. Then Go to `Build Phases`, and in the section `Link Binary With Libraries` add the file `build/libyaml.dylib`. Then in the `Copy Files` section, set `Destination` to `Executables`, clear `Subpath`, uncheck `Copy only when installing` and then again add `libyaml.dylib`.

Then you should be able to use `import Yaml` and `Yaml.load("")`.
