### ISSUE TITLE
Support for Swift 1.2

### ISSUE THREAD

**Issue by Riccardo99** [behrang/yaml.swift#4]
Hi, I want to use `yaml.swift` in my project on **XCode 6.3 Beta 2**, but I'm getting various errors while doing so. I tried to convert the code, but no success so far.

Can someone make a branch compatible to **Swift 1.2** or something?

Thanks :)

**Comment by behrang** [comment]
I don't get the relation to `yaml.swift`!?

**Comment by Riccardo99** [comment]
Sorry, my mistake, I copied the wrong name. I have edited the message, please, see it again.

**Comment by behrang** [comment]
Ok, it will be updated soon.
