### ISSUE TITLE
Ability to package as a framework

### ISSUE THREAD

**Issue by jpsim** [behrang/yaml.swift#5]
Since you already have a module map and a dynamic library, this should be pretty straightforward, and would simplify integration into Xcode projects (and add Carthage support at the same time!).

Thanks!

**Comment by behrang** [comment]
Framework is now created in the build directory.

Since my project is not an XCode project, I don't know if it is possible to add carthage support.

**Comment by behrang** [comment]
Moved to an Xcode project and added Carthage support.

@jpsim can you please check it give me feedback?
